### PR TITLE
Removed `self.logger.clone()` in filesink/filesrc

### PR DESCRIPTION
**Pull request by budziq**
Hi @sdroege,  

There is no contributing guideline so I went ahead and made a trivial PR. I hope it's ok.
I'm really interested in this project. Are you open for any form of contribution?

Best Regards,
Michał Budzyński

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks, I'll review that in a bit :)

I'll add a contributing guideline later also, of course I'm interested in all kinds of contributions :) if you have any example to point me to, please let me know

**Comment by budziq** [comment]
> I'm interested in all kinds of contributions

Excellent!

>  if you have any example to point me to, please let me know

Well most of the rust projects I contribute to don't have a separate contributing file unless one is really needed (like in the case of [rust-cookbook](https://github.com/rust-lang-nursery/rust-cookbook/blob/master/CONTRIBUTING.md)).

Typically a simple clause in readme about acceptable submission form and license suffices. But I guess that it's not really vital.
```markdown
## License

Serde is licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or
   http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or
   http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in Serde by you, as defined in the Apache-2.0 license, shall be
dual licensed as above, without any additional terms or conditions.
```

**Comment by budziq** [comment]
Most likely any if these suggestions would be a major overkill ;)

**Comment by sdroege** [comment]
Thanks, merged :) And also updated the README.md a bit.

**Comment by budziq** [comment]
Thanks very cool!

@sdroege do you have some speccific roadmap/idea for these plugins?
Like porting of some of the demuxers / decoders or typefinds or would you accept any "low hanging" plugin implementations that could show off easy pure rust implementattions?

**Comment by sdroege** [comment]
Currently the plan is to move to HTTPS://github.com/sdroege/gstreamer-rs for various internals, extend the API and finish the FLV demuxer (and get rid of the C code there). Then allow filters, and then we'll see what next :)

If you want to write any plugin, feel free to send a PR to add it here or keep it separate if you prefer that. As long as it's useful and not just an example, having it here would be nice.
What were you thinking of writing?

**Comment by budziq** [comment]
Well I've not give it much thought yet but here are some loose ideas:
- still image decoders/encoders based on [image crate](https://crates.io/crates/image) - basically all supported [image formats](https://github.com/PistonDevelopers/image#21-supported-image-formats) might be viable
- multifile sink/source reimplementation
- maybe look into the FLV demux implementation
- look into other demuxers / decoders that might be implemented with [nom](https://github.com/Geal/nom/issues/14) possibly [FLAC](https://github.com/sourrust/flac)

I don't have much time on my hands but I might tinker on some of these (or anything other you might suggest).

**Comment by sdroege** [comment]
That all sounds useful. Keep in mind though that most of this will require to first write new integration with the GStreamer base classes (GstVideoDecoder, GstVideoEncoder, GstAudioDecoder, GstAudioEncoder) or extensions/fixups of the existing ones (the demuxer, I'm planning to mostly rewrite that... especially to get rid of the C code).

My next plans are porting to gstreamer-rs, then porting the demuxer to plain Rust. Then I was going to write integration with GstBaseTransform for all kinds of filters, but I could also start with any of the above if that helps you and you don't want to do that yourself.


Instead of writing our own demuxers/decoders/decoders, these should all be a separate crate (like flavors already is), or using an existing crate out there (like the ones from rust-av, or the FLAC and Vorbis crates that exist already). No need to reinvent the wheel unless necessary, and these things would be useful for other people too.

**Comment by budziq** [comment]
IMHO, having gst-rs integrations for `GstVideoDecoder`, `GstVideoEncoder`, `GstAudioDecoder`, `GstAudioEncoder` and ` GstBaseTransform` would be a huge win for people with some rust experience and nearly zero gst knowledge to provide relatively large set of rust elements using available crates. Providing the integrations/fixups will most likely be over my head but I'll at least look into it. 

> Instead of writing our own demuxers/decoders/decoders, these should all be a separate crate (like flavors already is), or using an existing crate out there

Right. I was thinking of providing gst-rs elements that would just utilize existing crates like image/FLAC/etc and available integrations. Which in comparison would be the easiest and most approachable of the tasks you mentioned.

**Comment by sdroege** [comment]
My plan is to not directly have bindings for those GStreamer classes (well, that will be in gstreamer-rs to some degree), but similar to the existing Source/Sink traits have something more rusty. Something working with enums, not calling into other elements but having functions that do processing and just return a result.
Basically there should not be much GStreamer "weirdness" left in the API needed to implement such things, but still access be provided to do it if really necessary (via gstreamer-rs).

So if you want to work on that, just go ahead and let me know if you need help or want to discuss possible solutions/APIs :)

**Comment by sdroege** [comment]
I added tickets for all these things now

**Comment by budziq** [comment]
> I added tickets for all these things now

Great! Judging from you posts I guess that you have some short mid and long term ideas mapped. Would you be willing to make a loose "brain-dump" on some of the tickets? Even 2-3 sentences pointing to what needs to be done or what can be used as reference would be a great help to potential contributors (Unless actual implementation would be easier than the actual braindump which might be the case for a veteran :).

**Comment by sdroege** [comment]
No, all those things will need everybody more time to implement than to write the short ideas there :) For most things the first step would be to come up with a API design though. I'll add some infos to the tickets tomorrow or later, and also in gstreamer-rs

**Comment by sdroege** [comment]
Added info to all the tickets here, gstreamer-rs not yet.

**Comment by sdroege** [comment]
And also in gstreamer-rs now.

**Comment by budziq** [comment]
Thanks!

**Pull request closed without merging**
