### PR TITLE
Simple example of cellrenderer

### PR DESCRIPTION
**Pull request by vhdirk**
As promised, an example cellrenderer.
I've not bothered to implement all of the virtual functions. Just the render function, as that's the most visible one.

### CODE REVIEW

**Comment by sdroege** [comment]
There are various compiler warnings, can you fix those? Mostly about unused imports/functions/variables, but this ones here look problematic

```warning: functions generic over types must be mangled
   --> gtk-examples/src/cell_renderer.rs:185:1
    |
184 |   #[no_mangle]
    |   ------------ help: remove this attribute
185 | / pub unsafe extern "C" fn cell_renderer_new<T: CellRendererBase>()
186 | |      -> *mut T::InstanceStructType
187 | | where
188 | |     T::ImplType: CellRendererImpl<T>
...   |
192 | |     this as *mut T::InstanceStructType
193 | | }
    | |_^
    |
    = note: #[warn(no_mangle_generic_items)] on by default

```

**Comment by sdroege** [comment]
The travis failure is not your problem, I'll fix that some time later today :)

**Comment by vhdirk** [comment]
I wasn't using ```cell_renderer_new``` anyway, so I just removed it

**Comment by sdroege** [comment]
I've moved this to https://github.com/sdroege/gtk-subclass now

**Pull request closed without merging**
